# This file was generated by GoReleaser. DO NOT EDIT.
cask "better-webhook" do
  name "better-webhook"
  desc "Modern CLI for developing and testing webhooks"
  homepage "https://github.com/endalk200/better-webhook"
  version "1.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "better-webhook"

  on_macos do
    on_intel do
      url "https://github.com/endalk200/better-webhook/releases/download/v#{version}/better-webhook-darwin-x64.tar.gz"
      sha256 "030df6115250b2d5f62d015412cbe91b296ba3c6c48e40e078718c100e30989a"
    end
    on_arm do
      url "https://github.com/endalk200/better-webhook/releases/download/v#{version}/better-webhook-darwin-arm64.tar.gz"
      sha256 "0b53422b7a0a4aaed625ad392b1f652263812a2d0c32ecc2b2759bc9c277ff2c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/endalk200/better-webhook/releases/download/v#{version}/better-webhook-linux-x64.tar.gz"
      sha256 "ab91a34711069d1c28c0febfa8d229850a43063e3e1aad00f5f7a580f31bef49"
    end
    on_arm do
      url "https://github.com/endalk200/better-webhook/releases/download/v#{version}/better-webhook-linux-arm64.tar.gz"
      sha256 "b6b1ef0470b004a7a908cac6568925e8f3c97ddaa86f43f9586c2319de70013d"
    end
  end

  # No zap stanza required
end
