# This file was generated by GoReleaser. DO NOT EDIT.
cask "better-webhook" do
  name "better-webhook"
  desc "Modern CLI for developing and testing webhooks"
  homepage "https://github.com/endalk200/better-webhook"
  version "1.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "better-webhook"

  on_macos do
    on_intel do
      url "https://github.com/endalk200/better-webhook/releases/download/v#{version}/better-webhook-darwin-x64.tar.gz"
      sha256 "1e218f98cfe87f0918d05bae2c8ac0013cc31a6ba5c85cba9c9db10781ceebdf"
    end
    on_arm do
      url "https://github.com/endalk200/better-webhook/releases/download/v#{version}/better-webhook-darwin-arm64.tar.gz"
      sha256 "b71ef9d2c9f262f356b2cfbc871ae81f3bbc2448db5978de0904ffc63af74db7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/endalk200/better-webhook/releases/download/v#{version}/better-webhook-linux-x64.tar.gz"
      sha256 "c40031db6c5783e75da00c6dd8fe616eac23e2e8b88c8b242b6e8842099de63d"
    end
    on_arm do
      url "https://github.com/endalk200/better-webhook/releases/download/v#{version}/better-webhook-linux-arm64.tar.gz"
      sha256 "cb39d28ee27f1ec8ccbad59ffa068b45d3f23fb99eb498f477abbf9e1bd71927"
    end
  end

  # No zap stanza required
end
